/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LanguageCode } from '../../models/language-code';

export interface GetLocalizationApiLocalizationLangCodeGet$Params {
  lang_code: LanguageCode;
}

export function getLocalizationApiLocalizationLangCodeGet(http: HttpClient, rootUrl: string, params: GetLocalizationApiLocalizationLangCodeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getLocalizationApiLocalizationLangCodeGet.PATH, 'get');
  if (params) {
    rb.path('lang_code', params.lang_code, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getLocalizationApiLocalizationLangCodeGet.PATH = '/api/localization/{lang_code}';
