/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { pingApiPingGet } from '../fn/operations/ping-api-ping-get';
import { PingApiPingGet$Params } from '../fn/operations/ping-api-ping-get';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `pingApiPingGet()` */
  static readonly PingApiPingGetPath = '/api/ping';

  /**
   * Ping.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `pingApiPingGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  pingApiPingGet$Response(params?: PingApiPingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return pingApiPingGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Ping.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `pingApiPingGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  pingApiPingGet(params?: PingApiPingGet$Params, context?: HttpContext): Observable<string> {
    return this.pingApiPingGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
