/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getLocalizationApiLocalizationLangCodeGet } from '../fn/localization/get-localization-api-localization-lang-code-get';
import { GetLocalizationApiLocalizationLangCodeGet$Params } from '../fn/localization/get-localization-api-localization-lang-code-get';

@Injectable({ providedIn: 'root' })
export class LocalizationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getLocalizationApiLocalizationLangCodeGet()` */
  static readonly GetLocalizationApiLocalizationLangCodeGetPath = '/api/localization/{lang_code}';

  /**
   * Get Localization.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLocalizationApiLocalizationLangCodeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLocalizationApiLocalizationLangCodeGet$Response(params: GetLocalizationApiLocalizationLangCodeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return getLocalizationApiLocalizationLangCodeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Localization.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLocalizationApiLocalizationLangCodeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLocalizationApiLocalizationLangCodeGet(params: GetLocalizationApiLocalizationLangCodeGet$Params, context?: HttpContext): Observable<any> {
    return this.getLocalizationApiLocalizationLangCodeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
