/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PortalRole } from '../models/portal-role';
export interface PortalRoleList {
  roles: Array<PortalRole>;
}
