/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PortalRole } from '../models/portal-role';
export interface ShowUser {
  disabled?: (boolean | null);
  email?: (string | null);
  fullname?: (string | null);
  id: number;
  roles: Array<PortalRole>;
  username: string;
}
