/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserRequest {
  email?: (string | null);
  fullname: (string | null);
  username: (string | null);
}
