/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserCreateRequest {
  disabled?: (boolean | null);
  email?: (string | null);
  fullname?: (string | null);
  password: string;
  username: string;
}
