/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PortalRoleList } from '../../models/portal-role-list';
import { UpdatedUserResponse } from '../../models/updated-user-response';

export interface AddPortalRoleApiUsersUserIdRolesPost$Params {
  user_id: number;
      body: PortalRoleList
}

export function addPortalRoleApiUsersUserIdRolesPost(http: HttpClient, rootUrl: string, params: AddPortalRoleApiUsersUserIdRolesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdatedUserResponse>> {
  const rb = new RequestBuilder(rootUrl, addPortalRoleApiUsersUserIdRolesPost.PATH, 'post');
  if (params) {
    rb.path('user_id', params.user_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdatedUserResponse>;
    })
  );
}

addPortalRoleApiUsersUserIdRolesPost.PATH = '/api/users/{user_id}/roles';
