/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPassword } from '../../models/user-password';

export interface ChangePasswordApiUsersPasswordUserIdPatch$Params {
  user_id: number;
      body: UserPassword
}

export function changePasswordApiUsersPasswordUserIdPatch(http: HttpClient, rootUrl: string, params: ChangePasswordApiUsersPasswordUserIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, changePasswordApiUsersPasswordUserIdPatch.PATH, 'patch');
  if (params) {
    rb.path('user_id', params.user_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

changePasswordApiUsersPasswordUserIdPatch.PATH = '/api/users/password/{user_id}';
