/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdatedUserResponse } from '../../models/updated-user-response';
import { UpdateUserRequest } from '../../models/update-user-request';

export interface UpdateUserByIdApiUsersPatch$Params {
  user_id: number;
      body: UpdateUserRequest
}

export function updateUserByIdApiUsersPatch(http: HttpClient, rootUrl: string, params: UpdateUserByIdApiUsersPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdatedUserResponse>> {
  const rb = new RequestBuilder(rootUrl, updateUserByIdApiUsersPatch.PATH, 'patch');
  if (params) {
    rb.query('user_id', params.user_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdatedUserResponse>;
    })
  );
}

updateUserByIdApiUsersPatch.PATH = '/api/users/';
